pipeline:
  identifier: Build_gosample_1737502291070
  name: Build gosample
  orgIdentifier: default
  projectIdentifier: samplayground
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Samgithub
        repoName: gosample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: SscaArtifactSigning
                  name: Artifact Signing_1
                  identifier: ArtifactSigning_1
                  spec:
                    source:
                      type: docker
                      spec:
                        connector: samdockerhub
                        image: samarthsud/gosample:latest
                    signing:
                      type: cosign
                      spec:
                        private_key: sam-private-key
                        password: sam-cosign-password
                    uploadSignature:
                      upload: true
              - step:
                  type: SscaArtifactVerification
                  name: Artifact Verification_1
                  identifier: ArtifactVerification_1
                  spec:
                    source:
                      type: docker
                      spec:
                        connector: samdockerhub
                        image: samarthsud/gosample:latest
                    verifySign:
                      type: cosign
                      spec:
                        public_key: sam-cosign-public
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kubernetes_connector_for_at
              namespace: ssca-at
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
